spring.application.name=employee
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect
# spring.datasource.url=jdbc:mariadb://localhost:3306/employee_directory

#docker
spring.datasource.url=jdbc:mariadb://db:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.main.banner-mode=off

#only shows the warn and error logs
#logging.level.root=warn

# add logging configs to display SQL statements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# COnfigure JPA/Hibernate to auto create the tables
# update will keep the data in the table
spring.jpa.hibernate.ddl-auto=update

# This exposes a /actuator/prometheus endpoint that Prometheus will scrape.
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true